#!/bin/bash

set -eo pipefail

if [[ -z "$BITBUCKET_USERNAME" || -z "$BITBUCKET_APP_PWD" ]]; then
  echo 'Missing a required environment variable $BITBUCKET_USERNAME or $BITBUCKET_APP_PWD'
  exit 1
fi


CLU_BRANCH=$(git symbolic-ref --short -q HEAD)
BB_REPO=$CI_PROJECT_USERNAME/$CI_PROJECT_REPONAME
# Remove first two lines and escape string for json
DESCRIPTION=$(echo "$1" | sed -n '1,2!p' | jq -aRs .)
TIMESTAMP=$(date +"%Y-%m-%d-%H-%M")

generate_post_data()
{
  cat <<EOF
{
  "title": "Update Composer dependencies ($TIMESTAMP)",
  "description": $DESCRIPTION,
  "close_source_branch": true,
  "source": {
    "branch": {
      "name": "$CLU_BRANCH"
    }
  }
}
EOF
}

curl -s https://api.bitbucket.org/2.0/repositories/$BB_REPO/pullrequests \
  -u $BITBUCKET_USERNAME:$BITBUCKET_APP_PWD \
  -X POST \
  -H 'Content-Type: application/json' \
  -d "$(generate_post_data)" > /dev/null
